version: '3'

services:

  git:
    image: 'git'
    build: './src/git'
    ports:
      - '2020:22'

  github-release:
    image: 'github-release'
    build: './src'

  www:
    image: 'tmvdl/projects:apply'
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '8000:80'

  api:
    build: './src/api'
    volumes:
      - './src/api:/app'
      - './data:/data'
    environment:
      - 'PORT=80'
      - 'DATA_PATH=/data'
    ports:
      - '8080:80'
